studyabroadapplication/urls.py
from django.contrib import admin
from django.urls import include,path    
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search', include('haystack.urls')), # 全文检索框架
    path(r'user/', include('user.urls',namespace='user')),
    path('', include('universitylist.urls',namespace='universitylist')),
    path('favicon.ico',RedirectView.as_view(url='/static/img/favicon.ico')),   
]

universitylist/urls.py
from django.urls import path,include
import re
from django.conf.urls import url
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns
router = DefaultRouter()
# router.register(r'api','universitylist',views.Api,basename="api") 
router.register('api',views.Api) 
router.register('bpi',views.Bpi)   #所以如果viewset类(第二个参数)中没用queryset属性，必须设置basename
app_name = 'universitylist'
urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    ## 根据view.后面的参数确定对应的视图， path('', views.index, name='index'，这样也可以
    path('map',views.Map.as_view(), name='map'),
    url('api/', include(router.urls)),
    path('ajax', views.ajax, name='ajax'),
    #path('api/', views.Api.as_view(), name='api'),
    path('universitylist/<int:university_id>/', views.detail, name='detail'),
]
urlpatterns += router.urls

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    {# 网页标题内容块 #}
    <title>{% block title %}???{% endblock title %}</title>
    <!--
            <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'jquery.min.js' %}"></script>
    <!--<script src="{% static 'bootstrap.min.js' %}"></script>-->
    {% block style %}{% endblock style %}
    <style>
        #container {
            margin-top: 50px;
            width: 100%;
            height: 800px;
        }

        #header {
            width: auto;
            height: auto;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 40px;
            background: #417690;
            color: #ffc;
            overflow: hidden;
        }

        .pagenation {
            height: 32px;
            text-align: center;
            font-size: 0;
            margin: 30px auto;
        }

            .pagenation a {
                display: inline-block;
                border: 1px solid #d2d2d2;
                background-color: #f8f6f7;
                font-size: 12px;
                padding: 7px 10px;
                color: #666;
                margin: 5px
            }

            .pagenation .active {
                background-color: #fff;
                color: #43a200;
                border: 1px solid #43a200;
            }

        .clearfix:after {
            visibility: hidden;
            display: block;
            content: "";
            clear: both;
            height: 0;
        }

        .thumb-right, .thumb-right-flush {
            float: right;
            margin: 0 0 10px 10px;
        }

        .map-thumb:after {
            width: 103px;
            height: 19px;
            position: absolute;
            top: 0;
            right: 5px;
            content: "";
            background: url(/static/images/ah/enlarge-map.png) no-repeat left top;
        }

        .t-slack {
            margin-bottom: 15px;
        }

        .icon-wrapper {
            width: 35px;
            display: inline-block;
            float: left;
            margin-left: 4px;
        }

        .icon-website {
            background-position: 0 -64px;
            width: 26px;
            height: 23px;
        }

        .directory-data {
            margin-left: 46px;
            margin-top: 20px;
        }

        .h-taut {
            margin-bottom: 5px;
        }

        .rank {
            color: #222;
            border-radius: 0;
            text-shadow: 0 1px 0 #fff3cc;
            background: linear-gradient(to top left, #e0b938, #f7dfa1, #e0b938);
            display: inline-block;
            padding: .55em .25em;
            min-width: 2em;
            font-weight: bold;
            font-size: 14px;
            line-height: 1;
            float: right;
            margin: 0 -5px 0px 0;
        }
        .info a{
            color: #ffc;
            margin-left:0;
            margin-right0;
            padding:0;
        }
        .info span{
            color: #ffc;
            margin-left:0;
            margin-right0;
            
        }
        .info a:hover{
            color: black;
            text-decoration:none;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation" id="header">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">SAAMIS</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav" id="mynav">
                    <!-- 广告，算法推荐的项目,比较优秀的项目 -->
                    <li id="home"><a href="/index"><span class="glyphicon glyphicon-home "></span> Home</a></li>
                    <!--周边商场,推荐项目-->
                    <li><a href="/map"><span class="glyphicon glyphicon-map-marker"></span> Search by map</a></li>
                    <!-- 收藏自己的喜欢的项目 -->
                    <li><a href=""><span class="glyphicon glyphicon-star"></span> Conditional query</a></li>
                    <li><a href="#support"><span class="glyphicon glyphicon-headphones"></span> Donation</a></li>
                    <!--  个人介绍什么的，请求赞助，可以放支付宝二维码-->

                </ul>
                <div id="login">
                    {% if user.is_authenticated %}
                    <div>

                        <div style="float:right;margin-top:8px;" class="info" id="dropdownMenu1" data-toggle="dropdown">
                            welcome：<em>{{ user.username }}</em>
                            <span>|</span>

                            <a style="margin-right:20px"  href="{% url 'user:userinfo' %}">userinfo</a>
                            <span>|</span>
                            <a style="margin-right:20px" role="menuitem" tabindex="-1" target="_blank" href="{% url 'user:favorite' %}">collect</a>
                            <span>|</span>
                            <a style="margin-right:20px" role="menuitem" tabindex="-1" href="{% url 'user:history'  %}">history</a>
                            <span>|</span>
                            <a style="margin-right:20px" role="menuitem" tabindex="-1" href="{% url 'user:logout'   %}">logout</a>
                        </div>
                    </div>
                    {% else %}
                    <a href="{% url 'user:login' %}" class="btn btn-default" style="float:right;margin-top:8px" id="register-button">login</a>
                    <a href="{% url 'user:register' %}" class="btn btn-default" style="float:right;margin-top:8px" id="login_button">register</a>
                    {% endif %}
                </div>
            </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
    </div>
    <div style="margin-top:50px"></div>


    {% block body %}

    {% endblock body %}


    {# 网页底部html元素块 #}
    {% block bottom %}

    {% endblock bottom %}
    {# 网页底部引入文件块 #}



    <script>
        'use strict';//在strict模式下运行的JavaScript代码，强制通过var申明变量，未使用var申明变量就使用的，将导致运行错误。
        window.onresize = function () {
            //console.log(Width");
            if ($('#home').css('float') === 'left') {
                $('#login').css('display', '');
            } else {
                $('#login').css('display', 'none');
            }
        }
        window.onload = function () {

            $('#mynav li').click(function () {//激活点击的菜单栏
                $('#mynav>li').removeClass("active");
                $(this).addClass("active");
            });
        }

    </script>
    <script>
        $('#ajax').click(function () {

            $.get('/ajax', {
                name: 'Bob Lee',
                check: 1
            });
        });
        $('#reset').click(function () {
            $('#test-form').slideToggle(3000);
        });

        $(function () {
            $('#s1').mousemove(function (e) {
                $('#ispan').text(e.pageX + '*' + e.pageY);
                console.log($('#login').offset().top);

            });
        });


        var testHasCss = function (obj, cssStr) {
            if ((obj).css(cssStr) === undefined) {
                return false;
            } else {
                return true;
            }
        }
        var Width = window.innerWidth//浏览器窗口的内部宽度（包括滚动条）

            || document.documentElement.clientWidth

            || document.body.clientWidth;

        var Height = window.innerHeight//浏览器窗口的内部高度（包括滚动条）
    </script>
    {% block bottomfiles %}


    {% endblock bottomfiles %}






</body>
</html>

templates/collect.html
{% extends 'base.html' %}
{% block title %}collect{% endblock title %}

{% block body %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="border:1px solid black">
            <h1 style="text-align:center">collect</h1>
            <table class="table table-striped">
                <tr>
                    <td>number</td>
                    <td>name</td>

                </tr>
                {% if university_list %}

                {% for university in university_list %}
                <tr>
                    <td>{{university.id}}</td>
                    <td><a href="{% url 'universitylist:detail' university.id %}">{{university.name}}</a></td>



                </tr>
                {% endfor %}
                {% endif %}
            </table>

        </div>
    </div>
</div>



{% endblock body %}


{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}

templates/history.html
{% extends 'base.html' %}
{% block title %}userhistory{% endblock title %}

{% block body %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="border:1px solid black">
            <h1 style="text-align:center">history</h1>
            <table class="table table-striped">
                <tr>
                    <td>number</td>
                    <td>name</td>

                </tr>
                {% if university_list %}

                {% for university in university_list %}
                <tr>
                    <td>{{university.id}}</td>
                    <td><a href="{% url 'universitylist:detail' university.id %}">{{university.name}}</a></td>



                </tr>
                {% endfor %}
                {% endif %}
            </table>

        </div>
    </div>
</div>



{% endblock body %}


{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}index{% endblock title %}
{% block body %}
<div class="container">
    <div class="row">
        <h2 style="text-align:center">
            {# topics.paginator.number_pages 返回总页数 #}
            University
            Page {{ universities.number }} of {{ universities.paginator.num_pages }}
        </h2>
        <div class="row" style="text-align:center">
            <form method="get" action="/search">
                <input type="text"  name="q" placeholder="search university">
                <input type="submit" name="" value="search">
            </form>
        </div>
        <div class="col-md-12" style="border:1px solid black">
            <table class="table table-striped" style="">
                <thead>
                    <tr>
                        <th>latest_rank</th>
                        <th style="text-align:center ">name</th>
                        <th>website</th>
                    </tr>
                </thead>
                <tbody>
                    {% for university in universities.object_list %}
                    <tr>
                        <td style="width:5px;text-align:center ">{{university.latest_rank}}</td>
                        <td style="width:350px;height:50px"><img style="width:38px;height:25px" src='static/img/flag/{{university.country }}.jpg' /><a href="{% url 'universitylist:detail' university.id %}">{{university.name}} </a></td>
                        <td>{{university.website}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="pagenation">
                <p id="page" align="center">
                    {% if universities.has_previous %}
                    <a href="?page={{ universities.previous_page_number }}" id="previous"><</a>
                    {% endif %}
                    {# universities.paginator.page_range 这个函数返回包含一个所有页码数的 range 对象 #}
                    {# 即 range(1, topics.paginator.num_pages + 1) #}
                    {% for page_number in pages %}
                    {% ifequal page_number  universities.number %}
                    <a href="?page={{ page_number }}" class="active">{{ page_number }}</a>
                    {% else %}
                    <a href="?page={{ page_number }}">{{ page_number }}</a>
                    {% endifequal %}
                    {% endfor %}
                    {% if universities.has_next %}
                    <a href="?page={{ universities.next_page_number }}" id="next">></a>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
<!--<script>
    var re = /(\d+)$/;
    var cnum = 1;
    if (re.exec(window.location.href) !== null) {
        cnum = Number(re.exec(window.location.href)[0]);
    }
    console.log(cnum);
    $('#page').children().eq(cnum).css("color", function () { return "red"; });
    console.log();
    $('#next').click(function () {
        var num = $('p a').last().text();
        var re = /(\d+)$/;
        var cnum = 1;
        if (re.exec(window.location.href) !== null) {
            cnum = Number(re.exec(window.location.href)[0]);
        }
        if (cnum < num) {
            window.location.href = '?page=' + String(cnum + 1);
        }
    })
    $('#previous').click(function () {
        var num = $('p a').last().text();
        var re = /(\d+)$/;
        var cnum = 1;
        if (re.exec(window.location.href) !== null) {
            cnum = Number(re.exec(window.location.href)[0]);
        }
        if (cnum > 1) {
            window.location.href = '?page=' + String(cnum - 1);
        }
    })
</script>-->
{% endblock body %}
{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}
<script>
    $("#mynav").find('li').eq(0).addClass("active");
</script>
{% endblock bottomfiles %}

templates/login.html
{% extends 'base.html' %}
{% block title %}login{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        {% if errmsg %}
        <h1 style="text-align:center">{{errmsg}}</h1>
        {% else %}
        <h1 style="text-align:center">login page</h1>
        {% endif %}
        <div class="jumbotron" style="margin:0 auto;width:50%;text-align:center">
            <form class="form-horizontal" role="form" method="post" action="/user/login/">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">username</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username" value="{{ username }}" placeholder="input your username">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password" name="password" placeholder="input your password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="remember" name="remember" {{ checked }}>remember
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">login</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock body %}


{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}

templates/map.html
{% extends 'base.html' %}
{% load static %}
{% block title %}map{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <!--<link rel="stylesheet" href="https://a.amap.com/jsapi_demos/static/demo-center/css/demo-center.css" />-->
        <div id="container"></div>
        <!-- 加载地图JSAPI脚本 -->

    </div>
</div>
{% endblock body %}
{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}
<script src="https://webapi.amap.com/maps?v=1.4.15&key=ad54c0ce51f7f04161eda3788cb842ac"></script>
<script>
            
    var map = new AMap.Map('container', {
        resizeEnable: true, //是否监控地图容器尺寸变化
        zoom: 8, //初始化地图层级
        center: [-73.9983, 40.7257],//初始化地图中心点
        //lang:'zh_en',
        lang:'en',
    });
    var onMarkerClick = function (e) {
        infoWindow.open(map, e.target.getPosition());//打开信息窗体
        //e.target就是被点击的Marker
    }

    {% for university in universities %}
    var marker{{ university.id }} = new AMap.Marker({
        position: new AMap.LngLat({{ university.longitude }}, {{ university.latitude}}  ),
        title: '{{university.name}}',
        // content: '{{university.name}}',

    });
    marker{{ university.id }}.on('click', markerClick{{ university.id }});
    function markerClick{{ university.id }}(e) {
        console.log('{{university.name}}');
        window.open("{% url 'universitylist:detail' university.id %}")
    }
    map.add(marker{{ university.id }});
    // marker{ { university.id } }.on('click', onMarkerClick);
    {% endfor %}
    //var marker = new AMap.Marker({
    //    position: new AMap.LngLat(  -71.1041,   42.3656),   // 经纬度对象，也可以是经纬度构成的一维数组[116.39, 39.9]
    //    title: 'Massachusetts Institute of Technology'
    //});

    //// 将创建的点标记添加到已有的地图实例：
    //map.add(marker);

    // 移除已创建的 marker
    //map.remove(marker);
    $("#mynav").find('li').eq(1).addClass("active");

        
</script>
{% endblock bottomfiles %}

templates/register.html
{% extends 'base.html' %}
{% block title %}register{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        {% if errmsg %}
        <h1 style="text-align:center">{{errmsg|safe}}</h1>
        {% else %}
        <h1 style="text-align:center">register page</h1>
        {% endif %}
        <div class="jumbotron" style="margin:0 auto;width:50%;text-align:center">
            <form class="form-horizontal" role="form" method="post" action="/user/register/">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">username</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username" placeholder="input your username">
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">email</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="email" name="email" placeholder="input your email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password" name="password" placeholder="input your password">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password2" class="col-sm-2 control-label">repeat password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password2" name="password2" placeholder="input your password again">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="allow" name="allow">Agree to user agreement
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">register</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>


{% endblock body %}


{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}

templates/static_index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}index{% endblock title %}
{% block body %}
<div class="container">
    <div class="row">
        <h2 style="text-align:center">
            {# topics.paginator.number_pages 返回总页数 #}
            University
            Page {{ countries.number }} of {{ countries.paginator.num_pages }}
        </h2>
        <div class="col-md-12" style="border:1px solid black">
            <table class="table table-striped" style="">
                <thead>
                    <tr>
                        <th>number</th>
                        <th>name</th>
                        <th>flag</th>
                    </tr>
                </thead>
                <tbody>
                    {% for country in countries.object_list %}
                    <tr>
                        <td style="width:5px">{{country.id}}</td>
                        <td><a href="{{country.id}}/">{{country.name}}</a></td>
                        <td><img style="width:38px;height:25px" src='static/img/flag/{{country.name}}.jpg' /></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p id="page" align="center">
                {% if countries.has_previous %}
                <a href="?page={{ countries.previous_page_number }}" type="button" class="btn btn-primary btn-lg " id="previous">previous page</a>
                {% else %}
                <a href="" type="button" class="btn btn-primary btn-lg " id="previous">previous page</a>
                {% endif %}
                {# countries.paginator.page_range 这个函数返回包含一个所有页码数的 range 对象 #}
                {# 即 range(1, topics.paginator.num_pages + 1) #}
                {% for page_number in countries.paginator.page_range %}
                {% ifequal page_number  country.id %}
                {{ page_number }}
                {% else %}
                <a href="?page={{ page_number }}">{{ page_number }}</a>
                {% endifequal %}
                {% endfor %}
                {% if countries.has_next %}
                <a href="?page={{ countries.next_page_number }}" type="button" class="btn btn-primary btn-lg " id="next">next page</a>
                {% else %}
                <a href="" type="button" class="btn btn-primary btn-lg " id="next">next page</a>
                {% endif %}
            </p>
        </div>
    </div>
</div>
<script>
    var re = /(\d+)$/;
    var cnum = 1;
    if (re.exec(window.location.href) !== null) {
        cnum = Number(re.exec(window.location.href)[0]);
    }
    console.log(cnum);
    $('#page').children().eq(cnum).css("color", function () { return "red"; });
    console.log();
    $('#next').click(function () {
        var num = $('p a').last().text();
        var re = /(\d+)$/;
        var cnum = 1;
        if (re.exec(window.location.href) !== null) {
            cnum = Number(re.exec(window.location.href)[0]);
        }
        if (cnum < num) {
            window.location.href = '?page=' + String(cnum + 1);
        }
    })
    $('#previous').click(function () {
        var num = $('p a').last().text();
        var re = /(\d+)$/;
        var cnum = 1;
        if (re.exec(window.location.href) !== null) {
            cnum = Number(re.exec(window.location.href)[0]);
        }
        if (cnum > 1) {
            window.location.href = '?page=' + String(cnum - 1);
        }
    })
</script>
{% endblock body %}
{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}

templates/university_detail.html
{% extends 'base.html' %}
{% block title %}{{university.name}}{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <table class="table table-bordered">
            <caption></caption>
            <tbody style="text-align:center">
                <tr>
                    <td colspan="4">
                        <h1 id="uid" ;style="text-align:center;font-size:xx-large" uname="{{university.id}}">
                            {{university.name}}
                            {%if is_collect %}
                            <span style="color:red" class="glyphicon glyphicon-heart " id="collect"></span>
                            {% else %}
                            <span class="glyphicon glyphicon-heart " id="collect"></span>
                            {% endif %}
                        </h1>
                    </td>{% csrf_token %}
                </tr>
                <tr>
                    <td>
                        <span class="rank">
                            #{{university.latest_rank}}
                        </span>

                    </td>
                    <td>
                        <h3>SAAMIS Universities</h3>
                    </td>
                    <td colspan="2" rowspan="6"> Mumbai</td>

                </tr>
                <tr>
                    <td colspan="2">
                        <h2>Address</h2>
                        <p>{{university.address}}</p>

                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h2>Website</h2>
                        {{university.website}}
                    </td>
                </tr>
                <tr>
                    <td colspan="2" rowspan="3">
                        <h2>Address</h2>
                        {{university.address}}
                    </td>


                </tr>
                <tr>
                </tr>
                <tr>
                </tr>
                <tr>
                    <td colspan="4">
                        <h2 style="text-align:center"> Summary</h2>
                        <p style=" text-indent:2em;">{{university.summary}}</p>

                    </td>

                </tr>
            </tbody>
        </table>

    </div>

</div>

{% endblock body %}


{# 网页底部html元素块 #}
{% block bottom %}

{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}

{% if not user.is_authenticated %}
<script>
    $('#home').removeAttr("class");
    $('#collect').click(function () {
        alert('login first');
    })
</script>
{% else %}
<script>
    $('#home').removeAttr("class");
    $('#collect').click(function () {
        if ($(this).css("color") === "rgb(51, 51, 51)") {
            $(this).css("color", "red");
            var university_id = $('#uid').attr("uname");
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = { 'university_id': university_id, 'csrfmiddlewaretoken': csrf, "type": "add" }
            $.post('/user/collect', params, function (data) {
                if (data.res == 0) {
                    alert(data.msg);
                }
                if (data.res == 1) {
                    alert(data.msg);
                }
            })      
        } else {
            $(this).css("color", "rgb(51, 51, 51)");
            var university_id = $('#uid').attr("uname");
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = { 'university_id': university_id, 'csrfmiddlewaretoken': csrf, "type": "minus" }
            $.post('/user/collect', params, function (data) {
                if (data.res == 2) {
                    alert(data.msg);
                }
            })
        }

    })
</script>
{% endif %}
{% endblock bottomfiles %}